spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        reset-enable: false
        login-username: ${DRUID_USER}
        login-password: ${DRUID_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
logging:
  level:
    root: INFO
    me.xuewen.chat: DEBUG
